version: '3'

networks:
  asist_net:
   external: true    
    
services:
  uaz_dialog_agent:
    image: uaz_dialog_agent:latest
    container_name: uaz_dialog_agent
    networks:
      asist_net:
        aliases:
          - uaz_dialog_agent
    entrypoint: sbt "runMain org.clulab.asist.RunDialogAgent mqtt mosquitto 1883"
